#!/usr/bin/env bash
# setup-github-repo-youtube-pipeline.sh
# Phase 0.1 of claude/1-YouTube-Pipeline-Workspace-Plan.md.
#
# Creates the GitHub repository that the generated youtube-pipeline workspace
# (its bundled .git-store bare clone) will push to in Phase 2.2, with a `main`
# default branch and basic branch protection on it.
#
# Deliberately does NOT push any code -- the generated project's own history
# lives in <output>/.git-store and is pushed later by hand (Phase 2.2). This
# script only provisions the empty remote and its protection rules.
#
# Requires: gh (authenticated with repo + admin:org where needed), jq.
# Run this from a shell where `gh auth status` succeeds -- per the plan's
# notes, gh is authenticated in the user's own terminal, not in the Claude
# session's environment, so the user runs this.
#
# Safe to re-run: repo creation is skipped if the repo already exists, and the
# protection call is idempotent (PUT replaces the rule set each time).

set -euo pipefail

OWNER="Wema-Digital"
REPO_NAME="youtube-pipeline"
SLUG="$OWNER/$REPO_NAME"
DESCRIPTION="YouTube keyword-intelligence and production pipeline -- multi-worktree workspace generated by vscode-workspace-gen"
DEFAULT_BRANCH="main"
VISIBILITY="--private"   # change to --public if this should be a public repo

command -v gh >/dev/null || { echo "gh is required -- install the GitHub CLI first"; exit 1; }
command -v jq >/dev/null || { echo "jq is required -- install it first (apt install jq)"; exit 1; }

echo "== 0. Auth check =="
gh auth status
gh auth setup-git

echo
echo "== 1. Create the repository (skipped if it already exists) =="
if gh repo view "$SLUG" >/dev/null 2>&1; then
  echo "  $SLUG already exists -- skipping creation."
else
  gh repo create "$SLUG" $VISIBILITY \
    --description "$DESCRIPTION" \
    --disable-wiki
  echo "  created $SLUG"
fi

echo
echo "== 2. Ensure the default branch is '$DEFAULT_BRANCH' =="
# A repo created empty (no --push, no --source) has no branches and no default
# ref until the first push. GitHub still records a `default_branch` name; set
# it now so the Phase 2.2 push lands on the branch we protect below.
CURRENT_DEFAULT=$(gh repo view "$SLUG" --json defaultBranchRef --jq '.defaultBranchRef.name // "main"')
if [ "$CURRENT_DEFAULT" != "$DEFAULT_BRANCH" ]; then
  gh api -X PATCH "repos/$SLUG" -f default_branch="$DEFAULT_BRANCH" >/dev/null || \
    echo "  (could not set default branch yet -- it will be '$DEFAULT_BRANCH' after the first push)"
else
  echo "  default branch already '$DEFAULT_BRANCH'"
fi

echo
echo "== 3. Branch protection on '$DEFAULT_BRANCH' =="
# KNOWN LIMITATION (confirmed 2026-08-29): the Wema-Digital org is on GitHub's
# free plan, which allows neither branch-protection rules nor rulesets on
# PRIVATE repos ("Upgrade to GitHub Pro or make this repository public").
# Decision: keep this repo private, accept no branch protection for now. This
# step will fail with HTTP 403 on a private free-plan repo -- that's expected,
# not a bug. It only does anything useful if the repo is made public or the
# org upgrades to Team.
#
# No explicit branch-protection convention is committed anywhere in
# coding-project-templates, so the baseline below is conservative: require a PR
# with one approving review, dismiss stale approvals, block force-pushes and
# deletions. Adjust to match whatever the org standardises on if it ever
# becomes applicable.
#
# Branch protection can only be applied to a branch that exists. If the repo is
# still empty, this step is skipped with a reminder.
if gh api "repos/$SLUG/branches/$DEFAULT_BRANCH" >/dev/null 2>&1; then
  gh api -X PUT "repos/$SLUG/branches/$DEFAULT_BRANCH/protection" \
    --input - >/dev/null <<'JSON'
{
  "required_status_checks": null,
  "enforce_admins": false,
  "required_pull_request_reviews": {
    "dismiss_stale_reviews": true,
    "require_code_owner_reviews": false,
    "required_approving_review_count": 1
  },
  "restrictions": null,
  "allow_force_pushes": false,
  "allow_deletions": false,
  "required_linear_history": false,
  "required_conversation_resolution": true
}
JSON
  echo "  protection applied to $DEFAULT_BRANCH"
else
  echo "  '$DEFAULT_BRANCH' does not exist yet (repo is empty) -- and on the"
  echo "  free plan, protecting a private repo is not available anyway. Skipping."
fi

echo
echo "== Done =="
echo "Repo:        $(gh repo view "$SLUG" --json url --jq '.url')"
echo "Clone URL:   $(gh repo view "$SLUG" --json sshUrl --jq '.sshUrl')"
echo
echo "Next (Phase 2.2, after the workspace is generated):"
echo "  cd <output>/.git-store"
echo "  git remote add origin \$(gh repo view $SLUG --json sshUrl --jq '.sshUrl')"
echo "  git push origin --all    # pushes every selected template's branch"
